### ISSUE TITLE
Create new Prod Environment for PO

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#103]
As the product owner for Blacklight, I need an environment configured so I can perform functional tests and provide product demonstrations to the stakeholders associated with the product. This should be in an environment other than the current Arch environment to avoid interferences between development and testing. 

- [x] Wearing my leadership hat, I would like for the new Prod Environment to be automated to ensure the environment can be quickly restored in the event of failure that requires complete restoration of the environment. (Provisioning)

- [x] Wearing my leadership hat, I would like for the new Prod Environment to be automated to ensure the environment can be quickly restored in the event of failure that requires complete restoration of the environment. (Deployment of the Code)

- [x] It was determined during Sprint 4 that Prod environment will not mirror Arch in terms of data or version since this environment is being used temporarily to store data related to the inventory of MARC Data Mapping.

- [x] I would like for the new environment to be named Prod unless the Technical Lead has another preference. The new name of the production environment is simply blackcat.library.emory.edu

**Comment by lovinscari** [comment]
@rotated8 - Can you please look at the Terraform and Ansible Tickets that would associated with this story? Each needed issue should be identified as a task (label) and linked to this story ticket.

**Comment by lovinscari** [comment]
We might want to look at what work is absolutely necessary to close/complete this story. @rotated8 - can you please look at the work included in this story to determine if any of this work could be reprioritized.

**Comment by SolomonHD** [comment]
#### Prod environment is fully functional with Shibboleth login working
There were several issues at play here:

- The solr-cor.internal.emory.edu address was being rejected due to strict security groups in place to prevent direct communication with solr unless the ec2 was curate or digital
 - The security groups for backend components (iiif, fedora, solr) have been relaxed and will now accept connections from all ec2s within VPC
- Shibboleth was not compatible with HTTP termination at the box, looking at working examples in DLP environments, they all had HTTPS termination on the ec2
  - HTTPS was enabled on the ec2

**Comment by rotated8** [comment]
For demo, will show the server running, commenting on the temporary url.
