### ISSUE TITLE
Display Availability on Single Item Record

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#124]
As the product owner, I would like to display availability on a single item record to begin testing real time availability functionality with Alma. 

- [x] To establish a prototype of this function the MMSID 9936612173702486 should be configured to display the single item record
- [x] If the book is available for check out according to the current status in Alma, the single item record should include the word Available in Green at the top of the record display.  
- [x] If the book is not available for check out according to the current status in Alma, the single item record should include the words Not Available in Red at the top of the record display.

**Comment by AGCooper** [comment]
https://developers.exlibrisgroup.com/blog/integrating-with-alma-s-real-time-availability-and-get-it/

**Comment by bwatson78** [comment]
As soon as my last PR (#145) has been merged, I'll move this into "To Accept".
