### ISSUE TITLE
Update Google Analytics tracking before 7/1/2023

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/blacklight-catalog#1306]
Universal Analytics is being replaced by Google Analytics 4. On July 1, 2023, standard Universal Analytics properties will stop processing new hits; we need to switch over to Goggle Analytics 4 before then. 

After July 1, 2023, we'll be able to access our previously processed data in our Universal Analytics property for at least six months; for longer term access we'll need to export this data.

More details:
[https://support.google.com/analytics/answer/11583528](url)
[https://support.google.com/analytics/answer/11583528#export](url)

Suggested tasks (needs more research):

- [ ] update to GA4 property
- [ ] test if custom event tracking still works
- [ ] build new reports if necessary
- [ ] export Universal Analytics data
- [ ] identify other remediations needed
