### ISSUE TITLE
Create Test Environment

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#132]
As a developer for Blacklight, I need an environment configured so I can deploy and test code before it goes to production. This should be in an environment other than the current Arch environment to avoid interference with infrastructure testing.

- [x] I would like for the new Test environment to be automated to ensure the environment can be quickly restored in the event of failure that requires complete restoration of the environment. (Provisioning)

- [x] I would like for the new Test environment to be automated to ensure the environment can be quickly restored in the event of failure that requires complete restoration of the environment. (Deployment of the Code)

- [x] I would like for the Test environment to mirror the environment setup on Arch so that functional testing is performed in the same manner as any tests performed on Arch.

- [x] I would like for the new environment to be named Test.

**Comment by SolomonHD** [comment]
Notes from Middleware transition board:

[Link] (https://app.zenhub.com/workspaces/middleware-transition-600b41cf051b7b001872d9cb/issues/emory-libraries/middleware-transition/11)

**Comment by libdgg** [comment]
Alternatives to Use AMI Plan:

LTDS Middleware is having issues with the create test/prod from an AMI of arch plan. The EC2s built from the AMI are not stable and are not serving the website correctly in HTTPS or HTTP mode. Even if LTDS somehow got it working I don't think this is the best solution, correct AMI building is a skillset the dept doesn't currently have. 


## Alterative plans:


### Build out blackcat using cor-cm, and lux-derived ansible scripts

#### Pros
- Probably the quickest solution, SH estimates 2-3 days for this work

#### Cons
- Forces usage of RHEL7, which are more expensive EC2s
- Not forward thinking (SH only one who runs cor-cm and he's leaving...)

### ML and MP build out new test by hand, ML creates Ansible scripts as they progress

#### Pros
- Ensures repeatability MP could build test by hand and ML prod by ansible, then compare
- Sustainable solution, end result will be script that ML or MP could comfortably run
- Can use cheaper AMZ Linux 2 EC2s

#### Cons
- May take a week or more to complete this work
- ML and MP schedules must align 


##### What SH has tried with the AMI:
- Disabling SSL entirely (force HTTP mode only)
- Disabling 80, (force HTTPS only)
- Recompile Passenger on the ec2
- Delete /opt/blackcat-catalog/ folder and recreate via cap deploy
- Copy /etc/http/conf.d/ssl.conf from curate-test and overwrite local AMI copy on ec2
- Generate new "localhost" keys so proper machine name is in the base apache cert/key
- Add CA (intermediate) Cert from InCommon. it was commented out on AMI base for some reason

**Comment by libdgg** [comment]
@mlooney please update this ticket with details about solutions for passenger

**Comment by SolomonHD** [comment]
#### Test environment is fully functional with Shibboleth login working
There were several issues at play here:

- The solr-cor-test.internal.emory.edu address was being rejected due to strict security groups in place to prevent direct communication with solr unless the ec2 was curate or digital
 - The security groups for backend components (iiif, fedora, solr) have been relaxed and will now accept connections from all ec2s within VPC
- Shibboleth was not compatible with HTTP termination at the box, looking at working examples in DLP environments, they all had HTTPS termination on the ec2
  - HTTPS was enabled on the ec2
