### ISSUE TITLE
Post-Recovery Checklist

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1382]
Arch, Test, and Prod should all pass these checks

- [ ] Does the application use a Solr collection named "blackcat_collection"?
- [x] Does Solr have a collection called "blackcat_hot_spare"?
- [x] Is the Solr collection "blackcat_collection" backed up daily?
- [ ] Is the Solr collection "blackcat_hot_spare" restored from a backup at the beginning of each month?
- [x] Does the application have incremental updates turned on?

**Comment by abelemlih** [comment]
@rotated8 all the requirements of this ticket have been fulfilled and it is ready to close.
