### ISSUE TITLE
Refine single item view page based on wireframe mockup

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#140]
As the product owner, I would like the single item view page to be refined based on the wireframe mockup attached so the development team, product owner, and stakeholders can begin assessing how data is displaying for various item records. The attached wireframe is based on "Blacklight Out of the Box" layouts since the intent is less about design and formatting at this point, and more about seeing the data in a single item record. 

- [ ] The wireframe is annotated detailing the various components of the layout. 

- [ ] Some of the components could simply be a block or words at this point for future content such as some page components have yet to be detailed as user stories with specific acceptance criteria.

- [ ] The primary focus of this prototype is the **Item overview** (1) and **Details** section (2). The data mapping for the various fields will be detailed in ticket #138. Note: the metadata output here is copied from what Primo currently displays and may be refined in future tickets.

---

- Wireframe: [Item Details - Metadata: Figma](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=564%3A7154)
- [Metadata Model Worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [View Item Detail: Metadata Sources translation](https://docs.google.com/document/d/1_qgOXn8SUzdrJOO0KD8IBvAmHFLymQ8K2GDQP1I1M90/edit#)

**Comment by rotated8** [comment]
As discussed:
- no tasks
- no styling, basic display only
- view tests

**Comment by devanshu-m** [comment]
Fields with questions for @lovinscari (will discuss tomorrow):

Publisher (location?), Related Names, Identifier, Subjects, Format, Publication info, Local Note, Source, Source Record ID - Call number?

**Comment by devanshu-m** [comment]
Draft PR and progress:
https://github.com/emory-libraries/blacklight-catalog/pull/183 

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/bf41d063-d71d-4c1d-ad87-632d5289742a)

**Comment by devanshu-m** [comment]
Publication info?

**Comment by devanshu-m** [comment]
Hi @lovinscari @eporter23  This is deployed to arch. This might not be perfect right now and will need improvements going forward, around displaying multiple fields within single labels.
