### ISSUE TITLE
STORY: Enable Online Borrowing/Accessing of Electronic Book for Emory Users

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#151]
As an Emory User, I have searched the catalog and found an electronic book that can be borrowed/viewed online according to the details of the single item display indicating the item is available, and can be accessed online.

- [ ] Ideally, I would like to see a link in the single item view display reading "Access Online" to the provider of the electronic book. 

- [ ] Because electronic books are only available to Emory users, I should be taken to a login screen if I am not logged in to the Blacklight application prior to selecting the "Access Online" link. 

- [ ] Once logged in, I should be redirected to the provider of the electronic book where I can view a sample or borrow the book.

- [ ] If selecting "borrow" my login credentials should be passed to the provider of the electronic book automatically (i.e., not requiring me to login again). 

- [ ] The transaction will end with a screen shot similar to that attached based on MMSID: 990035122570302486 which utilizes Overdrive. It does not appear that eBook borrowing shows in MyAccount (to be confirmed with Laura Akerman and/or Alex Cooper). ![Borrow_ElectronicBook.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/c5c0e472-bb7e-43b1-9b7a-a46a65a6c946)

**Comment by rotated8** [comment]
Deferring task breakout until after #125 is farther along.

**Comment by lovinscari** [comment]
This is not needed since the iFrame is in use. Will address later when a decision is made about API integration.
