### ISSUE TITLE
STORY: Provide examples of bibliographic records with multiple holdings

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#152]
As the product owner, I would like to provide examples of bibliographic records with multiple holdings so I can include with future stories for development. I would like assistance from the Core Systems team in finding examples for the scenario's listed below. It is assumed that each scenario could be an individual task. 

- [ ] One bibliographic record linked to one electronic article holding (from Alma)
- [x] One bibliographic record linked to multiple physical holdings (copies / locations)
- [x] One bibliographic record linked to multiple electronic holdings (this might not occur, but would be a case where more than one subscription platforms provide the same book)
- [x] One bibliographic record linked to one physical and one electronic holding
- [x] One bibliographic record linked to multiple physical holding and one electronic holding 
- [x] One bibliographic record linked to one physical holding and multiple electronic holding
- [ ] One bibliographic record linked to multiple physical and multiple electronic holdings

**Comment by norm0** [comment]
I'd love to get access to these examples for sample mockups/wireframes.

**Comment by libah** [comment]
Attached is a spreadsheet with examples for each scenario except for the 1st and last for which I could not find examples. [https://app.zenhub.com/files/295449627/7ec4b6a1-7ac6-4c05-947e-c36242ecc963/download](https://app.zenhub.com/files/295449627/7ec4b6a1-7ac6-4c05-947e-c36242ecc963/download)

**Comment by libah** [comment]
I added a spreadsheet that you can download directly from the ticket (#152). Please let me know if you have any problems.

--
Ann Hulton
LITS: Library Core Systems
Emory University
ann.hulton@emory.edu
470-249-4919
