### ISSUE TITLE
STORY - Create report(s) to provide examples of items in catalog that should not be deduplicated

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#153]
As the product owner, I would like reports and/or examples of items in catalog that should not be deduplicated based on previous conversations with stakeholders. Examples are provided below. It is assumed that each item could be considered an individual task. 

- [ ] Holdings in the Rose Library that share a bibliographic record with holding records at other locations (i.e. show the Rose copy as a unique record in searches)
- [ ] Holdings in the Rose Library that DO NOT share a bibliographic record with holding records at other locations, but share titles or ISBNs and would otherwise be deduplicated as part of Group 2 (i.e. exclude any Rose holdings from Group 2 rules and treat them as a unique record in searches)
- [ ] Any other uniquely significant copies that should not have Group 1 or Group 2 rules applied because of holding location, collection membership, or other predictably definable characteristic (each unique location or characteristic would need its own story)

**Comment by lisahamlett** [comment]
I have reached out to Elizabeth Roke for help answering these questions.

**Comment by laura-ake** [comment]
@lisahamlett See Alma normalization rules, Dedup rules, section t, assigning of "t99" code (do not dedup)  for conditions (or specific records)

**Comment by lisahamlett** [comment]
Reached out to Elizabeth again.  Will also do some evaluations myself.

**Comment by libah** [comment]
Attached is a spreadsheet/report with t99 rules[https://app.zenhub.com/files/295449627/9211a9ea-7127-4ce0-ab74-b6e8b2b7b40b/download](https://app.zenhub.com/files/295449627/9211a9ea-7127-4ce0-ab74-b6e8b2b7b40b/download)

**Comment by lisahamlett** [comment]
Example 1: Holdings in the Rose Library that share a bibliographic record with holding records at other locations.

9937264709502486
9937235817102486
9937234784602486


Example 2: Holdings in the Rose Library that DO NOT share a bibliographic record with holding records at other locations, but share titles or ISBNs

I don't have an example of this.  I have asked MARBL several times but they have not gotten back to me.


Example 3: Holdings in Pitts Special locations EXHIBIT (temp), SPCOL, SPOZ, SPDOZ, SPRES, SPPAM

9936672720002486
990026973580302486
990026758430302486

**Comment by tmiles2** [comment]
@lovinscari can we check-in with the SEND team during tomorrow's meeting for some additional examples.

**Comment by lisahamlett** [comment]
From Elizabeth:

A couple of notes about the RL deduping rules.  In general, we are ok if our holdings show with those in another library IF they are a holding on the same bibliographic record.  Our concern lies with items that dedup with another bibliographic record.  If those Rose Library has chosen to create a new bib, we do not want those records to dedup with a different bibliographic record even if the ISBN, title, author, edition, etc. are the same.  That’s usually because of very specific notes in our bibliographic record (such as inscriptions, etc.) that either makes deduping confusing or outright inaccurate.

The example Laura gave in Slack (Narrative of Frederick Douglass) is a good one, and can be problematic when e-books are matched with local copies that may have inscriptions, marking, or other characteristics that don’t match the digitized version.  Here’s another:

MMSID: 990022790860302486 (RL copy)
MMSID: 990005764550302486  (Woodruff/other)
MMSID: 990022252670302486 (Oxford/RL)
In this example the ISBN/Title/Author match but the edition statements are slightly different.  I suspect that deduping rules would cause these to normally dedup, but they shouldn’t.  

And one more (this is an example where we wouldn’t want our own copy to dedup with another copy we own:
MMSID: 990015544150302486 
MMSID: 990018909420302486

Also note that for items from the RL and other libraries that are on the same bib record, there are some requesting features that will need to be considered.  All RL items must be requested through Aeon.  This means that items that share the same bibliographic record may have different requesting workflows such as currently exists on MMSID 990009426060302486

**Comment by lisahamlett** [comment]
Ready for review by @lovinscari

**Comment by laura-ake** [comment]
Hi @lisahamlett @lovinscari I looked at this and looks good including Ann's report.  Wish I could've provided more examples but it was hard finding them, since we don't have a way I can see how things would dedup if we didn't have the block in Primo.  This is the one I provided in Slack, you might want to include it under "Example 2"  
Title: Narrative of Frederick Douglass, an American slave. Author:  Frederick Douglass 1818-1895.  Boston:  Published at the Anti-Slavery Office; 1845
MMSID   990030776370302486  (Rose Library copy)

MMSIDs  990033766100302486
990034545240302486
990024312740302486  are a "dedupmrg" cluster of 3 electronic records from Alma
