### ISSUE TITLE
STORY: Enable recall of physical item that is currently checked out to another patron

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#180]
As a library user, I would like the ability to recall a physical item from a patron. This process includes placing a recall on an item will send the borrower a notice that the book has been requested and must be returned sooner than the original due date.

- [ ] [Review documentation from ExLibris on recall requests](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/030Fulfillment/Resource_Requests/Recall_Requests)

- [ ] Work with Core Systems to determine current configurations in Alma for determining if an item is recallable, the recall period, how the requested item due date corresponds to the recall workflow, and how the cancelled recall due date is configured and corresponds tot he workflow.

- [ ] Configure a proof of concept using a single physical item that can be recalled according to current configurations in Alma. The proof of concept should include checking an item out to a member of the Scrum team within Alma and allowing another member of the scrum team to see the physical item is not available but provided a link titled "Recall this item" near the availability display. 
- [ ] Recall of items on loan are only available to an Emory User therefore a proposal of how to replicate this functionality to ensure only Emory Users with an Emory Shibboleth Login can recall the item should be included in the proof of concept.

- [ ] Once proof of concept functionality is confirmed, the recall from the member of the Scrum team can be cancelled but the unavailable status should remain while product owner performs functional test.

**Comment by lisahamlett** [comment]
Recalls are already enabled.  Let me know when you're ready to test and I will provide you with one for testing.

**Comment by lisahamlett** [comment]
@lovinscari Requests in the lightbox become recalls or work orders or whatever in Alma.  There's no difference from the patron side.

I was able to recall an item and it worked as expected.

**Comment by lisahamlett** [comment]
![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/9550803f-aa03-434a-a02c-3c42d6d3f468)
