### ISSUE TITLE
40% Request Physical Item (Hold / Recall)

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#188]
Definition of Done for Requesting a Physical Item:

Acceptance Criteria:

- [ ] All users (logged in and not logged in users) should be able to see items in the catalog including the availability of items that can be requested.

- [ ] Only authorized users should be presented with the option to request an item either from the search results view or the single item display view. 

- [ ] Users of the Blacklight Catalog should be authenticated with Shibboleth if an Emory User or Alma if an affiliate user. 

- [ ] Authorization to request an item should be based on current rules defined in the [Alma User Groups Report](https://docs.google.com/spreadsheets/d/12MOZtcZ4VmKo-I7XACV2P_A00YAkCi0FkV96jrHbDLA/edit?usp=sharing).

- [ ] Within the item record, the user should see what physical copies are owned, where they are held, and if the item(s) are available for requesting. 

- [ ] If multiple copies or multiple volumes within a single item record exist then the user should be able to request any copy or any volume associated with the item assuming the item is available and can be requested by the user (based on Alma User Group Rules).

- [ ] When requesting an item, the user should be presented with a new modal, window, or tab with a form that collects all data needed to complete the request in Alma including: pickup institution (Emory or Georgia Tech), the pickup location (drop down of all Emory University Libraries including Robert W. Woodruff Library Main Library, Robert W. Woodruff Library Outside Lockers, Law Library, Woodruff Health Sciences Library, Pitts Theology Library, Library Service Center, or Oxford College Library; Not needed after with a calendar option; a field to add a comment to the form. The form should have the options to Reset or Submit the form.

- [ ] Once the form is submitted, the request should show as a request on the users account visible when viewing My Account.
