### ISSUE TITLE
STORY: Configure Resource Type Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#194]
**Status:** existing facet, needs testing/confirmation

As an end user, I would like to search or browse materials by their overarching type, so that I can target my search only to books, videos, journals, etc.

**Acceptance criteria**

- [x] Facet heading should be “Resource Type”
- [x] Facet should follow the general functionality as noted in Facet - [general wireframe and Facet](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) - and [Facet Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on homepage and subsequent search result pages
- [x] Counts for the number of results should generally correlate to what displays in Primo currently
- [x] Values/terms shown in the facet correlate to standardized/controlled terms for major types of resources

**Metadata/SOLR notes**
Existing SOLR field: format_ssim

**Comment by devanshu-m** [comment]
This already exists in the app as required. No work necessary. Please confirm.

Homepage:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/0aeb8e64-d8e9-4fec-9b65-0053ba57b06e)

Search results page:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/fd242fe4-560a-4e25-af90-a5943aa8d494)

Expanded view:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/7051f550-66c9-4f68-b375-491ea86ba102)

**Comment by eporter23** [comment]
@devanshu-m FYI in testing this, Cari and I realized that we may need to revisit the terminology and mappings on some of the values, but we'll write that up as a new ticket once we have those requirements confirmed.
