### ISSUE TITLE
STORY: Configure Language Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#195]
**Status:** facet already exists: needs SOLR refinement

As an end user, I would like to search or browse materials by the language they were created in, so that I can target my search to match only specific languages

**Acceptance criteria**

- [x] Facet heading should be “Language”
- [x] Facet should follow the general functionality as noted in Facet - [general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on homepage and subsequent search result pages
- [x] Counts for matches should be similar to those currently shown in Primo for a given data set
- [x] Values/terms in the facet correlate to standardized/controlled terms for language names

**Metadata/SOLR notes**

- [x] SOLR field: language_facet_tesim: this field is currently used for the facet, but it is tokenized.
We should revise it or create a new field in the SOLR index so that the full phrase of the language name is searched (not tokenized into keywords in the case of a language name having more than one word)
- [x] Example: language code grc in the source MARC data should be searchable in the facet as the exact phrase “Greek, Ancient (to 1453)” 
- [x] see [placeholder field # 97](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) if we need to create a new SOLR field.

**Comment by eporter23** [comment]
If we do create a new SOLR field for this facet, I suggest we rename the existing one language_facet_tesim which contains the word "facet" to avoid confusion.

**Comment by rotated8** [comment]
@eporter23 From what I heard in sprint planning, we don't want tokenization (`_tesim`) for the facet, we'd use the full string (`_ssim`). It sounds like this is also the preference for the view. Is that correct?

I think @mark-dce was suggesting we index with tokenization and without in case we decide we want to use the tokenized version for something else later.

**Comment by eporter23** [comment]
@rotated8 yes, while the detailed item show page requirements aren't 100% finalized yet, my understanding is that for language, we'd use the same _ssim for both the facet and the display.

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/211

**Comment by rotated8** [comment]
@eporter23 I would recommend not adding "facet" to a fieldname for a field that will not be used for faceting.

**Comment by eporter23** [comment]
@lovinscari @devanshu-m this looks good to me. Tested on the multi-word examples such as "French, Old (ca. 842 - 1300)".
