### ISSUE TITLE
STORY: Configure Genre Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#198]
**Status:** new facet to be created

As an end user, I would like to search or browse resources by the genre or format of the material, so that I can narrow my search to match specific types of material within my area of research 

**Acceptance Criteria**

- [x] Facet heading should be “Genre”
- [x] Facet should follow the general functionality as noted in [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on search result pages only (not on homepage)

**Metadata/SOLR notes**

- [x] Need a new SOLR field for this that includes MARC 655 field only. See [placeholder field # 58](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236). 
- [x] Also need to remove 655 field from the subject facet field’s mapping when it is configured.
- [x] Genre terms should not be tokenized

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/214

**Comment by eporter23** [comment]
@devanshu-m @lovinscari this looks good!
