### ISSUE TITLE
STORY: Configure Region Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#199]
**Status**: facet exists; only needs stakeholder testing for any MARC subfield adjustments

As an end user, I would like to search or browse materials by geographic locations that are significant within the content itself, so that I can target my search to match specific regions related to my research

**Acceptance criteria**

- [x] Facet heading should be “Region”
- [x] Facet should follow the general functionality as noted in [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on search result pages only (not on homepage)

**Metadata/SOLR notes**
SOLR field: subject_geo_ssim

**Example output from current blackcat:**

- Ontario
- Africa, North
- Philadelphia (Pa.)
- South Asia
- Mediterranean Region
- Rome (Italy)
- Bolivia
- Oklahoma
- Islamic countries
- Guatemala
- Sri Lanka
- Ghana
- Lebanon
- Iowa
- Zimbabwe
- Sudan
- Arkansas
- Québec (Province)
- Congo (Democratic Republic)
- Byzantine Empire
-

**Comment by devanshu-m** [comment]
Facet already exists. Please confirm.

Search results page:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/f3b4665d-e2d2-482f-8285-5f54e68a1d63)

Expanded view:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/c5155402-de52-48d9-856c-d0ce93e0fba7)

**Comment by eporter23** [comment]
@lovinscari @devanshu-m this behaves as expected and includes the currently specified MARC mapping.
