### ISSUE TITLE
99% Basic Search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#20]
- [x] As a product owner representing various stakeholders, I would like an index that allows for searching and querying the index.
- [ ] In general, search queries of the index should interpret terms and parameters based on specific Marc fields to be approved by Emory University Libraries stakeholder community including SEND Team, and Libraries Cabinet.
- [ ] Search queries are expected to be precise especially when using advanced search queries that include multiple criteria in narrowing search results.
