### ISSUE TITLE
STORY: Congfigure Era Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#200]
**Status:** facet already exists; just needs acceptance testing or stakeholder input to identify any additional requirements needed.

**Acceptance criteria**

- [x] Facet heading should be “Era”
- [x] Facet should follow the general functionality as noted in [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on search result pages only (not on homepage)

**Metadata/SOLR notes**

- SOLR field: subject_era_ssim

**Example output from current blackcat:**

- 20th century
- 19th century
- 17th century
- 18th century
- 21st century
- Colonial period, ca. 1600-1775
- Civil War, 1861-1865
- 16th century
- Revolution, 1775-1783

**Comment by devanshu-m** [comment]
Already exists. Please confirm.

Search results page on arch:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/01b8b8a9-2e94-4158-b8c4-eaa290aeeb41)

Expanded view:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/c451367c-db7a-4ad1-a921-272e8c32da66)

**Comment by eporter23** [comment]
@lovinscari @devanshu-m this behaves as expected and includes the currently specified MARC mapping.
