### ISSUE TITLE
STORY: Configure Access Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#201]
**Status:** recently acquired is customized/dynamic in our current Alma/Primo setup. We could move forward with Online, At the Library first and break off Recently Acquired as a separate effort if needed.

- [ ] As an end user, I would like to narrow my search to focus on materials that have either on-site or online availability, so that I can quickly determine whether or not I may need to request material or can access it right away
- [ ] As an end user, I would like to limit my search results to show only newly added material, so that I can locate resources that I may not have already consulted

**Acceptance criteria**

- [x] Facet heading should be “Access”
- [x] Resources should be grouped into one or more categories: Online, At the Library, and Recently Acquired
- [x] The Recently Acquired search/query is presented along with Online/At the Library for grouping purposes (to consolidate facets)
- [x] Facet should follow the general functionality as noted in [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765) with the exception that the Recently Acquired search uses distinct logic than Online vs. At the Library -- Wireframe
- [x] Displays on search result pages only (not on homepage)
- [x] Counts for Online vs. Physical Resource and Recently Acquired should be similar to what is currently available in Primo for a given data set, building on prior tickets

**Metadata/SOLR notes**

- See SOLR field for Online vs At the Library: marc_resource_ssim [field # 12](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&range=12:12)
- Values for marc_resource_ssim should be renamed as “Online”, or “At the Library”
- See SOLR field for Recently Acquired: [Field ID # 73 on worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&range=63:63) (598 $a = NEW)
- OR, create a new Access field that combines these three values: Online, At the Library, Recently Acquired (placeholder field # 76)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/215
![Screen Shot 2021-02-15 at 11.24.59 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e1ecfa23-4a6a-43e7-b231-dfdd329e8302)
![Screen Shot 2021-02-15 at 11.25.22 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5bcd72ce-ceea-4b24-9651-9677f1167926)

**Comment by eporter23** [comment]
@lovinscari @bwatson78 this looks good to me! I am not the best person to test the online vs in the library counts but I have been spot checking the recently acquired results and they look on target.
