### ISSUE TITLE
STORY: Configure Library of Congress Classification Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#202]
**Status:** New facet needed

Story: As an end user, I would like to search or browse by major Library of Congress classification letters, so that I know more about the subject matter of the material as well as which floor of the stacks they might be on in the Woodruff Library or other libraries that use this classification

**Acceptance criteria:**

- [ ] Facet heading should be “LC Classification”
- [ ] Facet should follow general facet conventions and functionalities as noted in [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [ ] The main-level, single letter classification code should use shown for any matches, followed by a description of what the single digit letter represents (e.g. P - Language & Literature) as noted here: https://www.loc.gov/catdir/cpso/lcco/

**Metadata/SOLR notes**

- Existing SOLR field: lc_1letter_ssim as generated by the current marc indexer (values should not be tokenized). May need to map labels to letters.

**Example output:**

- P - Language & Literature			1,298
- Q - Science					114
- H - Social Sciences				85
- A - General Works				73
- G - Geography. Anthropology. Recreation	39
- More >>

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/222

![Screen Shot 2021-02-16 at 5.26.22 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/cb9082e3-d52d-4a7e-89e6-dd36dc507691)
![Screen Shot 2021-02-16 at 5.26.43 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f802540d-b7c4-4971-b099-be00085d86f6)

**Comment by eporter23** [comment]
@lovinscari spot checked this and it looks good. Note: with the recent work to include selected holdings data in the OAI feed, we might also be able to do more with call numbers of various types in the future.
