### ISSUE TITLE
STORY: Configure Publication/Creation Date Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#203]
**Status:** does not yet exist as a facet in black-cat; SOLR/indexing needed. _@eporter23 to Confirm with Metadata SMEs about local scenarios for fully unknown dates (are those recorded in 008?)_

As an end user, I would like to search for resources that were created or published within specific dates, so that I can limit my results to a period of time most relevant to my research question

**Acceptance criteria** 

- [x] Facet Heading should be “Publication/Creation Date”
- [x] Enable date range slider/plugin as needed such as is used by Lux
- [x] Recreate DLP functionality including ability to limit by entering dates manually
- [x] [Wireframe for Date Slider](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=115%3A186) facet

**Metadata/SOLR notes**

- Recommend creating a new normalized date for this, based on data in the 008 field, because existing pub_date_ssim is focused on publication specifically. Some resources in the catalog may be unpublished, but have other types of creation dates.
- See also prior work in ticket #97. 
- See [placeholder field # 87 on worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&range=55:55).
- Use date(s) provided in 008, position 7-10 and 11-14 (if populated, for date 2 of a date range)
- Normalize dates to years only (YYYY) if needed, as is done in the Lux application
- Normalize partially known/unknown dates into application readable date formats (such as EDTF, used in the Lux application)
- For 008 dates supplied with multiple dates, record these as multiple entries: one entry for each year in the range (as is done in currently in Lux: year_for_lux_isim?)

**Comment by rotated8** [comment]
For the Digital Library Project, we [index the enumerated years for an object](https://github.com/emory-libraries/dlp-curate/blob/main/app/indexers/curate_generic_work_indexer.rb#L93-L109) using a [special parser](https://github.com/emory-libraries/dlp-curate/blob/main/app/indexers/year_parser.rb)

**Comment by eporter23** [comment]
From prior work in #97: 

Missing 008 	845
008 Error 	132,316
260c Empty 	146,605
260c Error 	751
263c Empty 	6,629
264c Empty 	193,843
264c Error 	20,413

**Comment by bwatson78** [comment]
PR created: https://github.com/emory-libraries/blacklight-catalog/pull/220
![Screen Shot 2021-02-16 at 10.31.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/001b0bd8-2d3c-45f8-88b0-887fa21b9af8)
![Screen Shot 2021-02-16 at 10.32.05 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/941ed41a-5c0f-4387-9bc2-7762ef7c88bb)

@eporter23 Traject has a built in [method](https://www.rubydoc.info/gems/traject/2.3.1/Traject%2FMacros%2FMarc21Semantics.publication_date) that extracts the publication date. Please check that link to see if the logic works out for our needs.

**Comment by bwatson78** [comment]
From the method's description:

```
#marc_publication_date(options = {}) ⇒ Object
An opinionated algorithm for getting a SINGLE publication date out of marc

Prefers using 008, but will resort to 260c
If 008 represents a date range, will take the midpoint of the range, only if range is smaller than estimate_tolerance, default 15 years.
Ignores dates below min_year (default 500) or above max_year (this year plus 6 years), because experience shows too many of these were in error.
```

**Comment by eporter23** [comment]
Note for later: we should test how this works for serials/journals with an ongoing publication date.

**Comment by eporter23** [comment]
For the above example, this is treated as 1952 in the date slider. ![Screen Shot 2021-02-19 at 2.29.40 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7e1f15b1-a99f-4532-9acc-88e8babcb8f8)

**Comment by bwatson78** [comment]
@eporter23 Yeah, you're right. That's probably reinforcing the need to write our own logic.
