### ISSUE TITLE
STORY: Configure Library Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#204]
**Status:** does not yet exist; MARC/SOLR mapping needed

As an end user, I would like to search or browse materials by a specific library, so that I can target my search to a specific location that I may need to visit or utilize

**Acceptance criteria**

- [x] Facet heading should be “Library”
- [x] Facet should follow the general functionality as noted in[ Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on homepage and subsequent search result pages (wireframes)
- [x] Values/terms in the facet correlate to standardized/controlled terms for Library names

**Metadata/SOLR notes**

- New mapping needed for SOLR - see [field # 72 on worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&range=60:60)
- Library names need to be revised from the raw data to display-friendly versions (TBD)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/277

![Screen Shot 2021-02-25 at 9.27.35 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ee1ddde6-441c-4fd8-8f76-fcf5ac786f35)

![Screen Shot 2021-02-25 at 9.27.55 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8fdc71f0-993e-4523-8d15-2a482781e2b8)

**Comment by lovinscari** [comment]
I am accepting the ticket as is and will submit a new ticket for Emily to research refinements needed with mapping and recommendations needed so that the names of the libraries appear in a meaningful way to end users.
