### ISSUE TITLE
STORY: Configure Collection Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#205]
**Status:** there is already a Collection facet; may need mapping refinements based on stakeholder feedback

**Acceptance criteria**

- [x] Facet heading should be “Collection”
- [x] Facet should follow the general functionality as noted in [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on homepage and subsequent search result pages (wireframes)
- [x] Values/terms in the facet should not be tokenized

**Metadata/SOLR notes**

- [Placeholder field in worksheet: 75](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&range=64:64) 

The current mapping points to title_series_tesim, which may not be accurate. Confirmation needed from stakeholders.

**Comment by bwatson78** [comment]
Approved pseudocode:
```
If record's datafield tag == '710' && indicator == '2' && contains a subfield with tag == '5' that contains value == 'GEU'
    pull record's value for 'a'
else
    pull record's value for tag == '490', subfield 'a'
end
````

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/282

![Screen Shot 2021-02-25 at 3.56.47 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3f2672a1-54e3-4c03-a72d-1016bb93bd69)

**Comment by lovinscari** [comment]
@eporter23 - can you please review the data mapping when you return on 3/1/21?

**Comment by eporter23** [comment]
Looks good to me using the mappings I provided last week. May need refinements later.
