### ISSUE TITLE
STORY: Reindexing

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#209]
As a catalog patron, I would like to have the most up-to-date catalog data available to me, with as little interruption to catalog service as possible.

- [ ] Ability to reindex a single record?
- [ ] Ability to queue up an on-demand reindex
- [ ] Ability to queue up a full reindex
