### ISSUE TITLE
40% EPIC: View Digital Version Online

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#225]
View digital version or electronic resources available from Alma. Electronic resources include journals, eBooks, and streaming video. Decisions to be made include the use of the Alma Lightbox (iFrame). 

Definition of Done for Viewing Electronic Item

Acceptance Criteria:

- [ ] All users (logged in and not logged in users) should be able to see item records in the catalog.

- [ ] Only authorized users should be presented with the option to view the electronic item 

- [ ] Users of the Blacklight Catalog should be authenticated with Shibboleth if an Emory User or Alma if an affiliate user. 

- [ ] Authorization to request an item should be based on current rules defined in the [Alma User Groups Report](https://docs.google.com/spreadsheets/d/12MOZtcZ4VmKo-I7XACV2P_A00YAkCi0FkV96jrHbDLA/edit?usp=sharing).

- [ ] The accessibility of the electronic item could come either from the 856 field if a digitized version of the item is available or in the (@eporter23 - can you provide details) field if the electronic record is a redirection to the vendor site.

- [ ] The link or access to the electronic item should be in the single item view and perhaps the search results which would ideally link directly to the vendor site providing the electronic item or opening the full text. If using the services page, it is assumed the user will need to access thee services page before accessing the vendor site.
