### ISSUE TITLE
STORY: Performance test suite

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#253]
Users expect short page loads (under two seconds). To measure the application's ability to deliver the metric while under load, we must create and run an artificial performance test suite. The test suite must allow the load to be configurable.

Similar work was done for [Lux](https://github.com/emory-libraries/dlp-lux/tree/main#run-blacklight-performance-tests)

- [x] Write test suite
- [x] Run test suite with different loads against the Arch environment (or another one not connected to the production Solr cloud).
- [x] Report level where application fails to meet expectations (if found)

The suite should test the homepage, getting search results, and viewing an item.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/300

Tests: 
![Screen Shot 2021-03-04 at 2.03.49 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/776ff786-6577-4c24-bd29-51b1d66e2945)

**Comment by devanshu-m** [comment]
Successfully tested required scenarios.

When fetching large metadata show page:
Example (values are in ms)
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/de442e63-fa6e-4304-a198-55fd731b29ea)
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/5cb06c44-673a-4a5e-b439-e020763f1978)

Aggregate results:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/432761a7-4f9a-4e0d-a1cf-0033d3b9d4cf)

**Comment by devanshu-m** [comment]
Load test results when running non-GUI command:

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/1a70464f-381d-4a08-a3ba-d97ec6aed36b)

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/59c406f8-1e5e-45ae-b95d-d885c855f89f)

Please let me know if the above csv needs to go in a one drive folder
