### ISSUE TITLE
STORY: Automate Infrastructure Configuration - ARCH

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#254]
In order to facilitate environment setup, disaster recovery, and performance testing, we want infrastructure configuration to be automated.

- [x] Get new environment terraformed
- [x] Update tfm to use stock amzn2 AMI
- [x] ansible all required packages
- [x] verify ansible shibboleth config w/ apache
- [x] ensure new environment works with capistrano
- [x] create new solr core in solr-cloud installation
- [x] configure f5 rules to hit ALB
- [x] configure dns to refer arch to new environment
- [x] Configure Shibb for arch  
- [ ] rinse and repeat for test
- [ ] rinse and repeat for prod

**Comment by mlooney** [comment]
Hosts are automatically provisioned & deployed. Shibd is running & the apache module is loaded, and the shibboleth status check returns correct-looking values.


Handing off to Ann for F5 & dns configuration (after which we can more accurately test shibboleth)

**Comment by libah** [comment]
I requested the the dns cname through main IT services via ServiceNow.

**Comment by libah** [comment]
DNS cname is now pointing to blackcat-arch2.library.emory.edu. The F5 rules are setup.

**Comment by mlooney** [comment]
It appears the ALB/target group configuration needs modifying, though F5. Tracking down the terraform modules involved.
