### ISSUE TITLE
STORY: Assess additional requirements for system monitoring and alerts

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#264]
Once recommended work is completed with CloudWatch, the Infrastructure Team, Operations Lead and Technical Lead are asked to consider any remaining work including:

- [x] Honeybadger application integration
- [ ] Because this is a 24/7 environment, automated recovery should be included in the recommendation for the system monitoring and alerts.
- [ ] Exploration of the Ruby Gem (OK Computer)

**Comment by lovinscari** [comment]
Moving this under leadership responsibilities and out of backlog for the product.
