### ISSUE TITLE
STORY: Complete metadata mapping for single item display

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#268]
Status: Single item display initial metadata mapping has been completed but needs to be refined based on additional fields identified by stakeholders.

As an end user, I would like to see the display of a single item record that includes an overview of the item and more details of the item to ensure the item I am viewing is the exact item I want. 

Acceptance criteria

- [x] [Refine the Item Detail Template - Metadata Only](https://docs.google.com/document/d/1VFbatpccRFGczEz510oHQHQtLmjAXAk9hTR5az9fkDc/edit#) document to identify proposed Solr Fields for each numbered item identified in the document.

- [x] Confirm metadata alignment with members of the metadata subgroup including MARC fields identified for each Solr Field

- [ ] Document any changes needed with the Solr index in a new issue for the software engineering team.

- [x] Draft requirements and acceptance criteria for the development of the single item display that align metadata requirements with wireframes similar to that provided for facets to be reviewed with Norm, Emily and Cari prior to Sprint 7 planning on 3-11-21.

- [x] Confirm resource type mappings to inform wireframe and development (links to Materials pages)

Update: The Item Metadata Detail template has been reviewed and revised into a version 2 document (link updated above). This information will also be merged back into the Metadata Model worksheet and will be addressed in various tickets to be developed for Sprint 7.

**Comment by eporter23** [comment]
@lovinscari for resource type mappings, the MD subgroup has proposed some label revisions on the existing set of resource types mapped until additional requirements can be confirmed. I have also mapped those to equivalent Materials pages where applicable (not all have a matching page).

**Comment by eporter23** [comment]
@lovinscari for the mention of creating a new issue for SOLR revisions, I hope we can discuss prior to sprint planning about the best way to address this. It may be useful to break down the fields by section similar to how we did this for facets.
