### ISSUE TITLE
SPIKE: Determine work associated with implementing Browse Functions in Blacklight Catalog (post-beta)

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#272]
As the product owner, I would like to provide information to the Executive Sponsor (Metz) to determine the feasibility of implementing Browse functions in the Blacklight Catalog. Stakeholders have expressed real concern by not having this functionality in the application as we launch Phase 1 of the product. As such, I would like for the developer team to explore the work involved and time needed to implement the following:

Acceptance Criteria:

- [ ] Review the [Browse Search](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/010The_PNX_Record/150The_Browse_Section/030Browse_Search) knowledge article by ExLibris to gain a general understanding of the functionality.

- [ ] Further examine Browse Search currently configured in Primo that allows the end user to conduct browse search with the following parameters browse by other call numbers, browse by Dewey call number, browse by SUDOC call numbers, browse by NLM call numbers, browse by title, browse by subject, browse by author, browse by Library of Congress call numbers. The examination should include a discussion with Core Systems, software developers, and possibly members of the SEND Team to understand how the feature is used.

- [ ] Create a decision document that provides suggested methods for implementing and/or replicating the Browse Search function within Blacklight. The decision document should outline the expected functionality, the expected tasks involved with implementing the solution(s), the estimate of effort and time. The tasks should include not just the technical implementation but theming, branding, styling, receiving user feedback, and refinement. 

- [ ] Because of the amount of time needed to research and complete a detailed decision document, this SPIKE ticket should be time bound to a minimum of an 8.

**Comment by lovinscari** [comment]
I am closing this and will incorporate information into a new decision document.
