### ISSUE TITLE
STORY: Implement More Details section of View Record - Metadata Display

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#309]
As a catalog provider, I want to offer users a detailed view of metadata grouped into subsections, so that they can review increasing amounts of detail optionally

Note: This ticket establishes the markup and display of the overarching "More Details" section, heading and list structures needed for the More Details section of the wireframe. Subsections are detailed in separate tickets.

Dependency: Markup Review ticket

Mockups/references
- [Wireframe - Section 14](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0)
- [Emory pattern library](https://template.library.emory.edu/styleguide/patternlibrary/current/)
- [Emory digital collections markup](https://digital.library.emory.edu/catalog/774qjq2c3k-cor) and [bootstrap implementation](https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit#gid=0)
- Markup patterns - Follow framework from markup review [ticket #308]

Note: for this ticket we are mainly mocking up the larger HTML structure including sections, headings, subheadings, lists, etc.

Implement HTML markup for the new page section:
- [x] "More Details" heading
- [x] Metadata subsection headings -- placeholder: "Subject/Genre"
- [x] Lists of fields, labels and their contents: use placeholder field Genre: genre_ssim. 
- [x] Fields with multiple values should list each value on a new line)
- [x] Markup should align with accessibility best practices, SEO best practices, and existing Lux implementation where possible

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/337

![Screen Shot 2021-03-17 at 9.52.58 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b4630cd4-3a7c-4185-8364-407080fe8b43)
![Screen Shot 2021-03-17 at 10.05.23 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/32933ee8-0a1e-45ec-95eb-f093057492ad)
![Screen Shot 2021-03-17 at 10.08.01 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/406ad9d7-df7f-4fe5-9a0a-2b50686b9cf0)
![Screen Shot 2021-03-17 at 10.09.46 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/eca06c2c-fb86-4603-84f0-d59636252b18)

**Comment by lovinscari** [comment]
@eporter23 this looks good to me but ask that you please confirm metadata requirements. If acceptable to you, please accept and close the issue. Thanks!

**Comment by eporter23** [comment]
Looks great @bwatson78. @lovinscari there isn't really much in the way of metadata for this one, so much as getting the headings and HTML page structure in place - all good!
