### ISSUE TITLE
STORY: Implement Additional/Related Titles section of single item display

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#313]
Story: As an end user, I want to see more information about related or variant versions of a resource's title, so that I can assess its appropriateness to my research or navigate to related version of it

**Demoable examples**
https://blackcat-test.library.emory.edu/catalog/9936493491502486
https://blackcat-test.library.emory.edu/catalog/990036309240302486

**Mockups/References:**

- [Main Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0) 
- [Variant wireframe: show/hide behavior for long title entries](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=886%3A12771)
- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [Metadata sample with lots of titles](https://docs.google.com/document/d/1EqbDcZNjGkiO46ugjWls1mr2zo7vv1kzo-sHBgbT57U/edit) and overall [View Item - Metadata Details template](https://docs.google.com/document/d/1VFbatpccRFGczEz510oHQHQtLmjAXAk9hTR5az9fkDc/edit#) 
- Markup patterns - Follow framework from Markup Review tickets #308, #309

**Section Heading: Additional/Related Titles**

**Fields to display (label : SOLR fieldname)**

- [ ] 1. Full Title: title_addl_tesim
- [ ] 2. Uniform Title: New Field # 25
- [ ] 3. Former Titles: New field 117
- [ ] 4. Later Titles: New field # 121
- [ ] 5. Series Title: title_series_tesim
- [ ] 6. Collection: New Field # 119
- [ ] 7. Related/Included Titles: title_added_entry_tesim
- [ ] 8. Variant Titles: title_varying_tesim: 
- [ ] 9. Abbreviated Titles: title_abbr_tesim
- [ ] 10. Translated Titles: title_translation_tesim

**Display behaviors**

- Fields should be displayed in the order noted above
- If a field is not populated, it should not display
- If no fields in the section are populated, the accompanying section heading should also not display
- This section potentially has many detailed fields that will be of interest to a small number of specialist users. Selected fields will be visible by default; others are hidden but can be visible on-click by a user.
    - Related/Included Titles: title_added_entry_tesim: Hidden by default in a toggle-able set (see Main Wireframe, section 14b)
    - Variant Titles: title_varying_tesim: Hidden by default in a toggle-able set (see Main Wireframe, section 14b)
    - Abbreviated Titles: title_abbr_tesim: Hidden by default in a toggle-able set (see Main Wireframe, section 14b)
    - Translated Titles: title_translation_tesim: Hidden by default in a toggle-able set (see Main Wireframe, section 14b)
- Selected fields are also hyperlinked so that they run an exact phrase search (ssim fields):
    - Uniform Title: New Field # 25 
    - Former Titles: New field 117 
    - Later Titles: New field # 121: 

**SOLR/Mapping Revisions**

- See [Metadata worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) for more detail about mappings to revise or add
- Title_addl_tesim: Revised mapping; Include vernacular/alternate script versions; trim punctuation. 
- New Field # 25: New field mapping; Hyperlink to allow exact phrase search
- New field # 117:  New field mapping; Hyperlink to allow full phrase search
- New field # 121: New field mapping; Hyperlink to allow full phrase search
- title_series_tesim: Revised mapping
- New field # 119: subset of Collection facet mapping
- title_added_entry_tesim: Revised mapping and includes alternate script versions
- Title_varying_tesim: Revised mapping
- Title_abbr_tesim: Existing mapping
- Title_translation_tesim: revised mapping

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/342

![Screen Shot 2021-03-23 at 3.53.07 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/27c9382e-4126-4484-9818-7de480f489c8)
![Screen Shot 2021-03-23 at 3.53.50 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0ae22f38-5f07-4c65-8e48-8c146975d74e)
![Screen Shot 2021-03-23 at 3.54.26 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2590c584-8a0a-4681-be28-bf200f3618ca)
![Screen Shot 2021-03-23 at 3.55.08 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b324bcf6-5139-400a-a388-5f052f02ae46)
![Screen Shot 2021-03-23 at 3.55.40 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/82ba07f5-115e-4bf6-9536-bd98304fa856)

**Comment by eporter23** [comment]
@bwatson78 looks great so far in arch but I'm waiting to test against the full production set to see more title examples.

**Comment by eporter23** [comment]
@bwatson78 In testing this I realize I did not provide meaningful requirements around the hyperlinks for Former Titles and Later Titles. Currently, they are searching on themselves, which often sends the user in a circle back to the same record. These links should probably start a broader title search instead, but I'm not sure which field(s) that should include at the moment. I think we can close this as-is, but I'm going to check with @lovinscari to see about how we should alter the behavior moving forward.

**Comment by eporter23** [comment]
@bwatson78 closing this - will create a refinement ticket once we have nailed down the link behavior for Former and later Titles. Thanks for the hard work on this!
