### ISSUE TITLE
Configure Additional CloudWatch Alerting

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#403]
**STORY**
As part of an earlier spike, we have identified available disk space as a key metric to monitor and alert on.  For further details see #348 SPIKE: Determine what CloudWatch Metrics are available to set benchmarks on SOLR Performance.

**ACCEPTANCE**
The following statistics are being monitored (benchmarked) with alerts set as follows:
- [x] Solr disk utilization > 80% - #396
- [x] Web server disk utilization > 50% - #397
- [ ] JVM Heap Usage > 95% - 398
- [x] Solr system memory >= 100% - #399
- [x] Web server system memory >= 100% - #400
- [x] Solr CPU utilization > 90% - #401
- [x] Web server CPU utilization > 90% - #402

Notes:

- [Prior work on DLP monitoring for various applications](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/956)

**Comment by RachelDCE** [comment]
Taks: JVM Heap Usage > 95% - 398  has been carved out as a separate story to be completed in sprint 10.
