### ISSUE TITLE
Incident Support Model

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#488]
The scope of this epic ticket is operational support only for incidents and issues it does not include service requests, reports, development, enhancements, cost savings, or other types of operations. Although, one ticket to address how refinements will be monitored will be included as part of the overall workflow. The steps below are to develop a shared understanding of the incident support model and documentation needed to provide immediate support for incidents as well as onboarding and continuity for LTDS staff to provide incident support for the product or application.

- [x] Draft [Support Documentation on the Wiki](https://wiki.emory.edu/display/BDL/Operations)
- [x] Team review of support documentation to set a baseline for the support model and types of alerts needed. 
- [x] Draft tabletop exercise scenarios and schedule time to run them.
- [x] Conduct tabletop exercises to test the support model. Note any edits or changes needed.
- [x] Review notes from the tabletop exercises to develop a first draft of a support troubleshooting guide.

TICKET [23](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-launch/23)
- [x] ServiceNow Setup for CI, Assignment Group, KB Articles

TICKET [11](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-launch/11)
- [x] Team meeting to go over Product Refinement 1/28/2022
- [x] CL will schedule a follow-up meeting
- [ ] Outputs from the meeting would be a product enhancement guide and diagram

TICKET [1211](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1211)
- [x] Team meeting scheduled for 2/2/22
- [x] Tabletop to identify the process for supporting regular feedback (inspired by examples we are getting with feedback).
- [ ] Output will be information to put into a basic troubleshooting guide and any accompanying documentation or diagrams needed.

TICKET [1150 ](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1150)
- [ ] Review the [Support Troubleshooting Guide](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Scrum%20Team/Work%20Planning/2021-12-14_Blacklight_Support_Troubleshooting_Guide.docx?d=w5e3b624f081944dca8e052e26f85d95c&csf=1&web=1&e=HWyrth) with the team.

- [ ] Make any edits for the wiki documentation or the support troubleshooting guide. This will become version 1.0
- [ ] Identify any non-LTDS support unit/staff that will be needed and schedule meeting with them to go over the support model plan and get input. They will be looped in during the OLA steps that follow. This step is ensure if we need to run any exercises with external parties for support before finalizing version 1.0 of the support model or documentation.
- [ ] Move Support Troubleshooting guide into the wiki for on-call / paging personnel for initial troubleshooting and support.

TICKETS IN [EPIC 831](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/831) for Primo VE
- [x] Identify Primo VE documentation and configurations needed for the support model and support documentation.

TICKET [1202](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1202)
- [ ] Identify any scripts (e.g. [newly acquired items ticket](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1116)) that Library Search is dependent on and ensure those scripts are documented with permissions/access for the team to support them going forward.

TICKET [1184](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1184)
- [x] Doug and Cari meeting on 2/7/22 at 1pm to review this epic and prep for final tabletop exercise.
- [ ] Working meeting scheduled for 2/11/22 at 3 pm that will include review of troubleshooting guides and final round of tabletop exercises
- [ ] Recommended to then run second round of tabletop exercises using updated information to validate the model. Note any edits or changes. Alternatively, the LTDS support team can schedule weekly operational check-ins for the first 3 to 6 months after launch of the product or application to refine the support model and documentation over time and proceed with the remaining steps below. 
- [ ] Confirm any final access, permissions and setup for technicians needed for ongoing support and enhancement

TICKET [42](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-launch/42) and [43](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-launch/43)
- [x] Working meeting scheduled for 2/14/22 and 2/18/22
- [ ] Support Playbooks will be needed to inform the OLA

TICKET [1185](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1185)
- [ ] [Finalize the support process flow diagram](https://lucid.app/lucidchart/invitations/accept/inv_c3a1cae6-a58e-4584-8678-0d17b87601e2) (will be used for the OLA) 

TICKET [1186](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1186) and [28](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-launch/28)
- [x] Draft OLA meeting scheduled for 2/21/22 - [Working Draft of the OLA is here](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/LTDS-Technology%20Agreements/Drafts/OLA-Library-Search/OLA-LIBRARY-SEARCH-DRAFT-2022.docx?d=w662f03cffec845c4a6148f362c46456e&csf=1&web=1&e=dEVTBY).
- [x] Review OLA with LTDS team supporting the product for input and review. Meeting scheduled for 2/25/22
- [ ] Review OLA with any team external to LTDS for input and revise. [per ticket 28](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-launch/28)
- [ ] Final review of OLA with LTDS team to submit for approval.
- [ ] Review OLA with LTDS-L for approval. Include approval dates on the signature lines and update metadata. Make PDF of approved copy. Next scheduled review should be no more than 6 months for any new product or application.
- [ ] Post OLA in the approved folder of the [LTDS Technology Agreements OneDrive space](https://emory-my.sharepoint.com/:f:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/LTDS-Technology%20Agreements?csf=1&web=1&e=ztshG4). A word copy should be placed in the Drafts folder for any revisions for the next version. All copies in the Approved folder should be PDF with all signatures, dates, version and metadata complete.

TICKET [902](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/902)
- [ ] Identify and document in the wiki the Infrastructure, integrations, and development and deployment models for ongoing operations, future enhancements, and knowledge transfer. 

TICKET [1217](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1217)
- [ ] It was determined in ticket [#1118](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1116) that for now the process of updating newly acquired will be manual. 
- [ ] This information should be updated as part of the support playbooks to ensure all of Core Systems is aware of how the process runs. 

TICKET [1187](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1187)
- [ ] By this Thursday - identify the team and cadence and get meetings scheduled. Schedule monthly operational check-in meetings for the first 3 to 6 months as a transition period to revise any of the documentation, guides or support model. The support team and product manager can determine the cadence for routine OLA review (recommend at least once per year) once the initial transition period has ended. Any changes should be noted and the OLA should be revised and move through the approval process to ensure communications and awareness.

**Comment by libdgg** [comment]
Tentative meeting to regroup on this work scheduled for Monday 2021-11-15

**Comment by libdgg** [comment]
@rotated8 add Ayoub to Honeybadger

**Comment by libdgg** [comment]
NOTES: 2021-11-15
Reviewed documentation and diagram. Identified need to document expectations for application uptime and Product Management lifecycle. Discussed scenarios that we may run to identify gaps in our support model.

Possible playbook scenarios in our control 
- Application Down
- SOLR Down

Scenarios out of our control with a different escalation path
- Shibboleth
- F5
- AWS
- Ex Libris

**Comment by libdgg** [comment]
I am scheduling times for tabletop exercises to run through the support scenarios listed in the post above. Hopefully that will let us know where our support model is ready and where there are gaps.

**Comment by libdgg** [comment]
Draf Exercise Instructions and agenda here:
https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/_layouts/15/Doc.aspx?sourcedoc=%7B9056BE2D-9CEC-4413-9F7E-8971BF8F53B0%7D&file=Blacklight-Support-Tabletop-Exercise-2021.docx&action=default&mobileredirect=true

**Comment by libdgg** [comment]
@tmiles2 Cari and I met on 2021-12-14 and went over outcomes from the tabletop exercises and the recent after-hour alert for Library Search. We are working on next steps to meet with the team to review after we get back from the break. Will keep this ticket open to track the next steps.

**Comment by lovinscari** [comment]
Moving this under leadership responsibilities and out of backlog for the product.
