### ISSUE TITLE
Preliminary searchbox options

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#86]
_As [an experienced end user], I want to quickly enter my search terms while seeing options to limit them to a subset of information, so that my search will be more precise._

This ticket is a preliminary mockup of known basic catalog search box requirements in order to start testing basic search functionality.

The default Blacklight drop-down options (currently All Fields, Title, Author, Subject) should be changed to the following:

- [x] Keyword (default selection) - The Marc Fields identified with Keyword Search are detailed in Task #95
- [x] Title - The Marc Fields identified for Title Search are detailed in Task #92
- [x] Author/Creator - The Marc Fields identified for Author/Creator Search are detailed in Task #93
- [x] Subject - The Marc Fields identified for Subject Search are detailed in Task #94

![Screen Shot 2021-01-05 at 14.52.37.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/9555e0c7-8c73-4219-ad89-c05ee70d519a)

Search User Acceptance Criteria are detailed in other issues based on criteria provided by the SEND Team. Functional Testing can also be performed by members of the SEND Team, Primo Product Manager (Akerman), or members of Core Systems. 

[Figma file](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=143%3A3342)

**Comment by RachelDCE** [comment]
![Screen Shot 2020-12-15 at 2.30.23 PM.png](https://images.zenhubusercontent.com/5ca3faa0fed84050d0a7bcf8/0cca67ab-be13-4a37-a0eb-beac173ca86e)

**Comment by bwatson78** [comment]
Update: 
- Keyword work has been merged into `main`.
- Title and Author/Creator is in-progress.
- Subjects is ready for review.

**Comment by devanshu-m** [comment]
@lovinscari Tested with following scenarios for all four targets:

Please note if you are searching for a string that could be within an array, (for example, `title` is saved as a multivalued field, meaning it is an array of strings) you will need to put the exact search phrase/string/query in double quotes ("your search title"). But in case of numbers, those don't need to be quotes (for example, IDs, ISBN, etc.) even if they are saved in arrays. I don't know the reasoning or logic behind this yet, but will have better answers when we go into fuzzy/loose search tickets. 

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/ac6240d7-9957-420a-b2e6-36943005ed9d)
----
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/24e7a75b-4ff8-487c-9f67-8b79b0cc7c97)
----
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/180e67b6-0f78-47fd-9c7d-1174faa30932)
----
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/a9097e76-4f21-4b11-ad61-f33b1806c598)
