### ISSUE TITLE
Beta launch checklist

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#996]
Beginning noon on 10/26/21, confirm the tasks below have been completed in preparation of beta launch. Please check the box next to your name indicating the verification of the task. In the event of a failure, a post should be made to the blacklight-dce channel to verify the possible issue and resolution including the creation of a new High Priority ticket to resolve the issue.

- Production environment moved from behind VPN verified by accessing search.libraries.emory.edu without connected to VPN

- [x] @lovinscari 
- [x] @libdgg 
- [x] @tmiles2 
- [x] @eporter23 
- [x] @AGCooper 
- [x] @rotated8 

- Production environment pointing to production instance of Alma verified by conducting a search of a physical item (at the library assigned), accessing services page from search results and single item view of an item, requesting the physical item, confirming the request is showing in My Library Card, confirming access services of the holding library can see the request, cancel the request before it is fulfilled. NOTE: When placing the request, put a note in the comment for those in fulfillment that this is a test and should not be fulfilled. Alex Cooper can also check and confirm the item is showing as requested in Alma.

- [x] @lovinscari - Oxford and Pitts
- [x] @libdgg - LSC
- [x] @tmiles2 - Woodruff
- [x] @eporter23 - Health Sciences [created, confirmed, cancelled]
- [x] @AGCooper - Rose and Business?
- [x] @rotated8 - Woodruff

- Confirm loading of home page does not take longer than 7 seconds (previous benchmark)
- [x] @lovinscari 
- [x] @libdgg 
- [x] @tmiles2 
- [x] @eporter23 
- [x] @AGCooper 
- [x] @rotated8 

Confirm you can access and submit feedback via the feedback form on library search
- [x] @lovinscari 
- [x] @libdgg 
- [x] @tmiles2 
- [x] @eporter23 [submitted, but did not see it sent to the list serv?]
- [x] @AGCooper 
- [x] @rotated8 

Confirm you can send an email to librarysearch@emory.edu (assuming OIT has configured the distribution list).
- [x] @lovinscari 
- [x] @libdgg 
- [x] @tmiles2 
- [x] @eporter23 
- [x] @AGCooper 
- [x] @rotated8
